### ISSUE TITLE
Singularity execution problem

### ISSUE THREAD

**Issue by sebbruchmann** [bacpop/ggCaller#23]
Hi Sam,

I could not install ggCaller via conda and cannot use Docker so I tried the singularity option.
I downloaded the .sif file and ran ggCaller on 10 fasta files (for testing purposes) as follows:

`singularity exec --bind /home/MYDIRECTORY/ggCaller/:/mnt samhorsfield96_ggcaller_latest-2023-04-27-6c0a454e1c5c.sif /opt/conda/bin/ggcaller --refs /mnt/input.test
`
Unfortunately, ggCaller stops after a few seconds and I get the follwing error message:

```
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Traceback (most recent call last):
  File "/opt/conda/bin/ggcaller", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/ggCaller/__main__.py", line 436, in main
    db_dir = download_db()
  File "/opt/conda/lib/python3.9/site-packages/models/__main__.py", line 19, in download_db
    tar.extractall(module_dir)
  File "/opt/conda/lib/python3.9/tarfile.py", line 2045, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/opt/conda/lib/python3.9/tarfile.py", line 2086, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/opt/conda/lib/python3.9/tarfile.py", line 2161, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/opt/conda/lib/python3.9/tarfile.py", line 2190, in makedir
    os.mkdir(targetpath, 0o700)
OSError: [Errno 38] Function not implemented: '/opt/conda/lib/python3.9/site-packages/models/ggCallerdb'
```
input.gfa and input.color.bfg are written into my directory, .fmp files are written in my fasta directory

Any ideas what might have gone wrong?
Thanks

**Comment by samhorsfield96** [comment]
Closing as inactive.
